# Generated by Django 3.0.1 on 2020-02-05 19:50

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'O nome de usuario só pode conter letras, digitos ou os seguintes caracteres: @/./+/-/_', 'invalid')], verbose_name='Usuario')),
                ('slug', models.SlugField(blank=True, max_length=40, unique=True, verbose_name='atalho')),
                ('nivel', models.IntegerField(choices=[(5, 'OPERADOR'), (4, 'SUPERVISOR'), (3, 'BACKOFFICE'), (2, 'RECURSOS HUMANOS'), (1, 'DIRETORIA'), (0, 'TI')])),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta Ativo?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='É da Equipe?')),
                ('is_admin', models.BooleanField(default=False, verbose_name='É administrador do sistema?')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Funcionario', verbose_name='Funcionario')),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Gestor', verbose_name='Gestor')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
